In [3]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets,linear_model,discriminant_analysis
from sklearn.model_selection import train_test_split

In [4]:
#加载数据
def load_data():
    iris = datasets.load_iris()
    x_train = iris.data
    y_train = iris.target
    return train_test_split(x_train,y_train,test_size = 0.25,random_state = 0,stratify = y_train)

## 用库实现逻辑回归

In [5]:
def test_LogisticRegression(*data):
    x_train,x_test,y_train,y_test = data
    regr = linear_model.LogisticRegression()
    regr.fit(x_train,y_train)
    print('Coefficients: %s, intercept %s'%(regr.coef_,regr.intercept_))
    print('Score: %.2f'%regr.score(x_test,y_test))

In [7]:
x_train,x_test,y_train,y_test = load_data()
test_LogisticRegression(x_train,x_test,y_train,y_test)

Coefficients: [[ 0.39310895  1.35470406 -2.12308303 -0.96477916]
 [ 0.22462128 -1.34888898  0.60067997 -1.24122398]
 [-1.50918214 -1.29436177  2.14150484  2.2961458 ]], intercept [ 0.24122458  1.13775782 -1.09418724]
Score: 0.97


#### 逻辑回归模型参数
#### penalty指定正则化策略，l1或者l2
#### dual返回true为求解对偶形式
#### C指定罚项系数的倒数，越小正则化项越大
#### fit_intercept指定是否需要计算b值
#### max_iter迭代次数
#### solver最优化问题的算法 'newton-cg'牛顿法，'lbfgs'L-BFGS拟牛顿法，‘liblinear’使用liblinear，‘sag’使用一个啊啊啊算法,小数据用liblinear，大数据集用sag
#### tol判断迭代收敛与否的阀值
#### multi_class表示对多分类问题的策略，'ovr'采用one-vs-rest策略,'multinomial'直接采用多分类逻辑回归策略

### multi_class参数对分类结果的影响

In [9]:
def test_LogisticRegression_multinomial(*data):
    x_train,x_test,y_train,y_test = data
    regr = linear_model.LogisticRegression(multi_class='multinomial',solver = 'lbfgs')
    regr.fit(x_train,y_train)
    print('Coefficients: %s, intercept %s'%(regr.coef_,regr.intercept_))
    print('Score: %.2f'%regr.score(x_test,y_test))
#该策略只能使用牛顿的求解最优化问题的算法

In [10]:
x_train,x_test,y_train,y_test = load_data()
test_LogisticRegression_multinomial(x_train,x_test,y_train,y_test)

Coefficients: [[-0.38365872  0.85501328 -2.27224244 -0.98486171]
 [ 0.34359409 -0.37367647 -0.03043553 -0.86135577]
 [ 0.04006464 -0.48133681  2.30267797  1.84621747]], intercept [  8.79984878   2.46853199 -11.26838077]
Score: 1.00


### 对于参数C来说，随着C增大，准确率在上升，当C增大到一定程度，准确度保持不变

## 代码实现逻辑回归

## 逻辑回归损失函数 cost = -ylog(p)- (1-y)log(1-p) 当y=1或0，p = 1/(1 + e ^(-X * seita))

In [ ]:
def _sigmoid(t):#逻辑回归公式
    return 1./ (1 + np.exp(-t))
def fit_gd(self, X_train, y_train, eta=0.01, n_iters=1e4):
        """根据训练数据集X_train, y_train, 使用梯度下降法训练Linear Regression模型"""
        assert X_train.shape[0] == y_train.shape[0], \
            "the size of X_train must be equal to the size of y_train"

        def J(theta, X_b, y):#每一行的误差和
            y_hat = _sigmoid(x_b.dot(theta))
            try:
                return - np.sum(y*np.log(y_hat)+ (1 - y)*np.log(1 - y_hat))/len(y)
            except:
                return float('inf')

        def dJ(theta, X_b, y):#返回的是每个参数误差
            return X_b.T.dot(_sigmoid(x_b.dot(theta))- y) / len(X_b)

        def gradient_descent(X_b, y, initial_theta, eta, n_iters=1e4, epsilon=1e-8):

            theta = initial_theta
            cur_iter = 0

            while cur_iter < n_iters:
                gradient = dJ(theta, X_b, y)
                last_theta = theta
                theta = theta - eta * gradient
                if (abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):
                    break

                cur_iter += 1

            return theta

        X_b = np.hstack([np.ones((len(X_train), 1)), X_train])
        initial_theta = np.zeros(X_b.shape[1])
        self._theta = gradient_descent(X_b, y_train, initial_theta, eta, n_iters)

        self.intercept_ = self._theta[0]
        self.coef_ = self._theta[1:]

        return self